### PR TITLE
Fix ru locale (CP1252 → KOI8-R)

### PR DESCRIPTION
**Pull request by masterrr**

### CODE REVIEW

**Comment by brenes** [comment]
Must not we keep the words from the old version too? Are they wrong? My knowledge of russian language is zero so I'm trying to make sure we don't lose any support

**Comment by masterrr** [comment]
The old ones are just a unreadable mess in broken encoding. It often happens with Russian :smile: 

For now I myself just fixed it locally, providing csv from my fork. 

You can fix any wrongly encoded russian text by pasting it into the big text field on https://www.artlebedev.ru/tools/decoder/ and clicking the button beneath it.

**Comment by brenes** [comment]
Thanks for the explanation! :smile: 

I''ll try to make a new gem version including this fix and will put you in the CHANGELOG. Thanks for the help!

**Comment by masterrr** [comment]
Cool, thanks

**Pull request merged**
